#define SPRITE_SHIP1	 	QString("../../sprites/spriteShip1.png")
#define SPRITE_SHIP1_HIT	QString("../../sprites/spriteShip1Hit.png")
#define SPRITE_SHIP1_MOVE1	QString("../../sprites/spriteShipMove1.png")
#define SPRITE_SHIP1_MOVE2	QString("../../sprites/spriteShipMove2.png")
#define SPRITE_SHIP1_MOVE3	QString("../../sprites/spriteShipMove3.png")

#define SPRITE_SHIP2		QString("../../sprites/spriteShip2.png")
#define SPRITE_SHIP2_HIT	QString("../../sprites/spriteShip2Hit.png")
#define SPRITE_SHIP2_MOVE1	QString("../../sprites/spriteShip2Move1.png")
#define SPRITE_SHIP2_MOVE2	QString("../../sprites/spriteShip2Move2.png")
#define SPRITE_SHIP2_MOVE3	QString("../../sprites/spriteShip2Move3.png")

#define SPRITE_EXPLOSION1	QString("../../sprites/spriteExplosion1.png")
#define	SPRITE_EXPLOSION2	QString("../../sprites/spriteExplosion2.png")
#define SPRITE_EXPLOSION3	QString("../../sprites/spriteExplosion3.png")
#define SPRITE_EXPLOSION4	QString("../../sprites/spriteExplosion4.png")
#define SPRITE_EXPLOSION5	QString("../../sprites/spriteExplosion5.png")
#define SPRITE_EXPLOSION6	QString("../../sprites/spriteExplosion6.png")

#define SPRITE_CANNONBALL 	QString("../../sprites/spriteCannonball.png")
#define SPRITE_BULLET		QString("../../sprites/spriteBullet.png")
#define SPRITE_CURSOR		QString("../../sprites/spriteCursor.png")
#define TILE_WATER1			QString("../../sprites/tileWater1.png")
#define TILE_WATER2			QString("../../sprites/tileWater2.png")
#define TILE_LAND1			QString("../../sprites/tileLand1.png")
