######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 20 14:44:01 2012
######################################################################

QT += xml

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h tile.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp tile.cpp
